# Generated by Django 4.2.3 on 2023-07-26 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('data', models.DateField()),
                ('data_postagem', models.DateTimeField(auto_now_add=True)),
                ('descricao', models.TextField()),
                ('valor_entrada', models.DecimalField(decimal_places=2, max_digits=10)),
                ('foto_principal', models.ImageField(blank=True, null=True, upload_to='media/eventos/')),
                ('cep', models.CharField(max_length=8)),
                ('rua', models.CharField(blank=True, max_length=255, null=True)),
                ('numero', models.IntegerField()),
                ('cidade', models.CharField(blank=True, max_length=255, null=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_categoria', to='Eventos.categoria')),
            ],
        ),
    ]
