# Generated by Django 4.2.3 on 2023-07-26 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='foto_principal',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
