# Generated by Django 4.2.3 on 2023-08-31 11:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Eventos', '0002_evento_user_alter_evento_data_postagem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventos_usuario', to=settings.AUTH_USER_MODEL),
        ),
    ]
