# Generated by Django 4.2.3 on 2023-07-26 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos', '0002_alter_evento_foto_principal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='data_postagem',
        ),
    ]
