# Generated by Django 4.2.3 on 2023-07-27 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos', '0003_remove_evento_data_postagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='data_postagem',
            field=models.DateField(blank=True, null=True),
        ),
    ]
