# Generated by Django 4.2.3 on 2023-09-03 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos', '0004_alter_evento_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='hora_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
