# Generated by Django 4.2.3 on 2023-08-05 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos', '0004_evento_data_postagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='data_postagem',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
