# Generated by Django 4.2.3 on 2023-08-05 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos', '0005_alter_evento_data_postagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='numero',
            field=models.CharField(max_length=8),
        ),
    ]
