# Generated by Django 4.2.3 on 2023-09-06 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0002_remove_user_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='foto_background',
        ),
    ]
